### ISSUE TITLE
control card in dashboard

### ISSUE THREAD

**Issue by kar-ton** [krasnoukhov/homeassistant-tesy#14]
is it possible to add this wonderful boiler control card directly to the dashboard?
![Screenshot 2024-12-24 at 09-00-40 Overview – Home Assistant](https://github.com/user-attachments/assets/6ec324e4-4a21-46e9-9a70-ebd6e78d81ae)

**Comment by krasnoukhov** [comment]
I don't think so... This is called "more info" in home assistant terms. Anyway, not a question for this project since it's not related to the integration.
